### ISSUE TITLE
drbd-overview has been deprecated

### ISSUE THREAD

**Issue by harridu** [zabbix-deb/zabbix-check-drbd#5]
drbd-overview is no longer included. This breaks the discovery script. I would suggest to use 'cat /proc/drbd' instead.

**Comment by harridu** [comment]
Maybe something like this:
~~~
#!/bin/bash

comma=""
echo -n '{ "data": ['

for k in $(cat /proc/drbd | cut -d: -f1); do test -z "${k##[0-9]*}" && echo -n $comma "{ \"{#RES}\": \"$k\" }" && comma=","; done

echo ']}'
~~~

**Comment by istoph** [comment]
built into zabbix-check-drbd (0.1~dev4)

**Comment by istoph** [comment]
@harridu thanks for your help, the release is now available at: https://repository.chr.istoph.de/
